# Generated by Django 3.2.6 on 2021-09-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbCountMessages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMessages', models.IntegerField(verbose_name='Total de mensagens')),
            ],
        ),
        migrations.CreateModel(
            name='tbCountRooms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('totalRooms', models.IntegerField(verbose_name='Total de salas')),
            ],
        ),
        migrations.CreateModel(
            name='tbCountSessions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSessions', models.IntegerField(verbose_name='Total de sessões')),
            ],
        ),
        migrations.CreateModel(
            name='tbCountUsers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('totalUsers', models.IntegerField(verbose_name='Total de usuários')),
            ],
        ),
        migrations.CreateModel(
            name='tbMessagesRoom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=50, verbose_name='Nome da sala')),
                ('totalMessages', models.IntegerField(verbose_name='Total')),
            ],
        ),
    ]
