# Generated by Django 3.2.6 on 2021-10-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dim_usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id user')),
                ('nome_usuario', models.CharField(max_length=100, verbose_name='nome_usuario')),
                ('codigo_permissao', models.IntegerField(verbose_name='codigo_permissao')),
                ('descricao_permissao', models.CharField(max_length=50, verbose_name='descricao_permissao')),
            ],
        ),
    ]
