# Generated by Django 3.2.6 on 2021-10-08 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_dim_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactLoginPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_login', models.DateTimeField(verbose_name='data_login')),
                ('data_logoff', models.DateTimeField(verbose_name='data_logoff')),
                ('quantidade_acesso', models.IntegerField(verbose_name='descricao_permissao')),
            ],
            options={
                'db_table': 'fact_login_plataforma',
            },
        ),
        migrations.DeleteModel(
            name='tbCountMessages',
        ),
        migrations.DeleteModel(
            name='tbCountRooms',
        ),
        migrations.DeleteModel(
            name='tbCountSessions',
        ),
        migrations.DeleteModel(
            name='tbCountUsers',
        ),
        migrations.DeleteModel(
            name='tbMessagesRoom',
        ),
        migrations.AlterModelTable(
            name='dimusuario',
            table='dim_usuario',
        ),
        migrations.RenameModel(
            old_name='dim_usuario',
            new_name='DimUsuario',
        ),
        migrations.AddField(
            model_name='factloginplataforma',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.dimusuario'),
        ),
    ]
